remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "Yash Yadurai"
name: "Yash Yadurai"
description: "Personal site and intro page"
url: "https://yashyadurai.github.io"

author:
  name: "Yash Yadurai"
  avatar: "/assets/images/avatar.jpeg"
  bio: "A Tech Enthusiast, Developer"
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yashyadurai"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yashyadurai"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yashyadurai001@gmail.com"

markdown: kramdown
plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
